### PR TITLE
Change peach-web user to peach-web instead of www-data

### PR DESCRIPTION
**Pull request by mhfowler**
`/var/lib/peachcloud/config.yml` will be read and written by multiple services -- so perhaps we should make all peachcloud services belong to peach group, and then make resources which need access from multiple services belong to the peach group?

### CODE REVIEW

**Comment by mhfowler** [comment]
related PR here https://github.com/peachcloud/peach-config/pull/50

**Comment by mhfowler** [comment]
@mycognosist was there a reason peach-web was set to run as www-data:www-data ?

do you think running as peach-web:peach makes sense?

**Comment by mycognosist** [comment]
@mhfowler 

I believe `peach-web:www-data` is the most appropriate. We want `www-data` as the group since the `peach-web` service is fundamentally a web server. Then if the `peach-web` user is part of the `peach` group, they should have the required permissions to interact with the `/var/lib/peachcloud/config.yml` file.

**Comment by mhfowler** [comment]
@mycognosist in the latest PR I went with the peach-web:www-data you suggested, and added a postinst script to the debian folder which adds peach-web to the peach group so it has the permissions it needs.

**Pull request merged**
