### PR TITLE
Logout button

### PR DESCRIPTION
**Pull request by mhfowler**
This PR adds functionality for setting a password, resetting a password, and logging out using nginx http basic auth. 

Note that the nginx config is written in debian/postinst (which is used via apt-get install). In this file you can also see that the way you can declare public routes is kind of messy (as I believe you have to re-declare the localhost proxy for each public route) -- another reason that switching to a rocket-based-authentication in the future might be nicer. 

I also figured out how to implement a log-out button using javascript (the function is in common.js). but I couldn't figure out how to reliably do this without javascript. The way I could think of, was to render the page with a {{host}} variable so the logout button is like `<a href="http://user:logout@{{domain}}"></a>` but I couldn't find a way in rocket to easily supply a host variable to all routes, without manually going through each route and adding a request guard which gets the host of the request, and adding a host to its context::build function, which seems like a lot of typing. In other web frameworks I've used, there's usually some way to provide variables to all routes (which is useful for populating fields in the "base" template which all routes inherit from). I wonder if we could figure out a way to do this in rocket. 

Here are some screenshots of the reset_password and send_password_reset pages:

Screenshot from 2021-07-08 14-50-27

Screenshot from 2021-07-08 14-46-55

This is tested and working, the next step is to actually send the password reset link and temporary password out via ssb-dm (and to make a page for configuring who are the SSB ids who are admins for the device and will be messaged). 

cc @mycognosist

### CODE REVIEW

**Comment by mycognosist** [comment]
@mhfowler 

This looks fantastic! Great work.

"I wonder if we could figure out a way to do this in rocket."

Seems like a good thing to bookmark and then we can tackle it later.

**Comment by mycognosist** [comment]
@mhfowler 

One thing I've learned during my NGI-Pointer work which I don't think I've mentioned here: delete the branch using the button in the purple 'Pull request successfully merged and closed' box above. This can be done for all closed PR's in all of our repos to keep them neat and tidy (basically just having one or a small handful of active branches).

I don't expect you to go back through everything to delete branches. I'll work on that in due course.

**Comment by mhfowler** [comment]
@mycognosist aww cool, I was worried that deleting the branch would mean you wouldn't be able to see the diff for the PR anymore (with our current workflow of merge before review), but I just tried it out and see that's not the case. I'll start deleting them now after merging.

Is it true that you don't have any branches you're saving on any of the repos? If so then I can just start deleting all the extra branches too when I'm going to a repo

**Comment by mycognosist** [comment]
@mhfowler 

Hmm good question. I might have one on `peach-web` and one on `peach-network` (probably also `peach-monitor`). The safest option, although it is a bit tedious, is to only delete the branches for which PR's have been merged. I move on to a fresh branch after each PR.

**Pull request merged**
